# Config copied from
#  http://www.theautomatedtester.co.uk/blog/2012/using-travis-ci-for-building-and-testing-firefox-addons.html
# Use node_js because there are maybe more workers?
language: python
python:
  - "2.7"
addons:
  firefox: "35.0"
virtualenv:
  system_site_packages: true
install:
  - sudo apt-get -qq install libxml2-dev libxslt-dev python-dev libcurl4-openssl-dev python-lxml
  - pip install -r https-everywhere-checker/requirements.txt
before_script:
  - sh -e /etc/init.d/xvfb start
env:
  - DISPLAY=':99.0'
script:
  - ./test.sh
# In test-ruleset-coverage.sh (called by test.sh), we use a git log --since
# to test only files that changed since a certain date. Travis does a
# shallow clone to save time. Unfortunately, the shallow clone for some reason
# means that *all* the files under src/chrome/content/rules git listed in the
# git log. Deepening the clone fixes it for now, but we should dig deeper.
git:
  depth: 300
